### ISSUE TITLE
using this module in a node runtime cause a runtime error

### ISSUE THREAD

**Issue by iambumblehead** [coolgk/utils#23]
```bash
  ReferenceError: window is not defined

  › Object.getPkce (node_modules/oauth-pkce/dist/index.js:9:21)
```

it would be super cool if this module supported both browser and node runtime environments

**Comment by coolgk** [comment]
@iambumblehead  could you please provide an example use case for running in node runtime? Per RFC code verifiers should be generated by clients (frontend browsers) hence this module is for browsers only

**Comment by iambumblehead** [comment]
ok yes this package is a browser-only package and so this is a non-issue since it occurs in a node environment
